name: SandAndGravel
main: com.minecarts.sandandgravel.SandAndGravel
version: ${pom.version}
website: http://minecarts.com
author: Verrier
description: >
             A connect 4 style minigame for minecraft
commands:
  sag:
    description: Main command to access SandAndGravel
    usage: /<command> [clear]